version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=propertydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api/src:/app/src
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=propertydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  
   